addressbook/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from addressbook.views import ContactUpdateView
from addressbook.views import LoginView
from addressbook.views import ContactListView
from addressbook.views import ContactDeleteView
from addressbook.views import LogoutView
from addressbook.views import AjaxContactCreateView
from addressbook.views import AjaxContactUpdateView

from . import views

app_name = 'addressbook'
urlpatterns = [
	path('', login_required(ContactListView.as_view()), name='home'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('edit/<int:contact_id>', login_required(ContactUpdateView.as_view()), name='edit_contact'),
	path('delete/<int:contact_id>', login_required(ContactDeleteView.as_view()), name='delete_contact'),
	path('exportcsv/', views.export_csv, name='export_csv'),
	path('importcsv/', views.import_csv, name='import_csv'),
	path('login/', LoginView.as_view(), name='login'),
	path('add/', login_required(AjaxContactCreateView.as_view()), name='add_contact'),
	# path('testing/<int:contact_id>', login_required(AjaxContactUpdateView.as_view()), name='edit_contact')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('addressbook.urls'))
]

addressbook/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class Contact(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	contact_number = PhoneNumberField(default="+639171231234")
	address = models.CharField(max_length=255)

	def __str__(self):
		return self.first_name + " " + self.last_name

addressbook/forms.py
from django import forms
from phonenumber_field.modelfields import PhoneNumberField

from .models import Contact

class ContactForm(forms.ModelForm):
	address = forms.CharField(widget=forms.Textarea(
		attrs={
			'class': 'address'
		}))
	class Meta:
		model = Contact
		fields = ('first_name', 'last_name', 'contact_number', 'address')
		widgets = {
			'contact_number': forms.TextInput(attrs={'placeholder': 'eg: +639171231234'}),
			'address': forms.TextInput(attrs={'class': 'address'})
		}

	def set_layout(self):
		self._helper.disable_csrf = True

addressbook/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth import login as user_login
from django.contrib.auth import authenticate
from django.contrib.auth import logout as user_logout
from django.shortcuts import redirect
from django.urls import reverse_lazy
from tablib import Dataset
from .forms import ContactForm
from django.contrib.auth.forms import UserCreationForm
from tablib import Dataset
from .resources import ContactResource
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import FormView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from braces import views

from .models import Contact

# Create your views here.

class LoginView(FormView):
	template_name = 'addressbook/login.html'
	form_class = UserCreationForm

	def post(self, request, *args, **kwargs):
		if 'login' in request.POST:
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				user_login(request, user)
				return redirect('addressbook:home')
			else:
				return redirect('addressbook:login')


		elif 'signup' in request.POST:
			form = UserCreationForm(request.POST)
			if form.is_valid():
				form.save()
				username = form.cleaned_data.get('username')
				raw_password = form.cleaned_data.get('password1')
				user = authenticate(username=username, password=raw_password)
				user_login(request, user)
				return redirect('addressbook:home')

class ContactListView(ListView):
	model = Contact
	template_name = 'addressbook/home.html'
	form_class = ContactForm
	context_object_name = 'contacts'

	def get_queryset(self):
		queryset = Contact.objects.filter(user=self.request.user)
		return queryset

	def get_context_data(self, **kwargs):
		context = super(ContactListView, self).get_context_data(**kwargs)
		user = self.request.user
		contact_create_form = ContactForm()
		context.update({
			'form': contact_create_form
		})
		return context

class ContactUpdateView(views.JSONResponseMixin, UpdateView):
	model = Contact
	template_name = 'addressbook/edit_contact.html'
	form_class = ContactForm
	success_url = reverse_lazy('addressbook:home')

	pk_url_kwarg = 'contact_id'

	def post(self, request, *args, **kwargs):
		contact = self.request.POST
		print(contact)
		contact_id = contact['contact_id']
		user = self.request.user
		form = Contact()

		if contact_id:
			update_contact = Contact.objects.get(id=contact_id)
			update_contact.first_name = contact['first_name']
			update_contact.last_name = contact['last_name']
			update_contact.contact_number = contact['contact_number']
			update_contact.address = contact['address']

			update_contact.user = user
			update_contact.save()

			data = {}
			data['success'] = 'Contact Updated'
		return self.render_json_response(data)

	def get_object(self):
		contact_id = self.kwargs.get('contact_id', None)
		print(contact_id)
		return get_object_or_404(Contact, pk=contact_id )


class ContactDeleteView(views.JSONResponseMixin, DeleteView):
	model = Contact
	template_name = 'addressbook/delete_contact.html'
	success_url = reverse_lazy('addressbook:home')

	pk_url_kwarg = 'contact_id'

	def post(self, request, *args, **kwargs):
		contact = self.request.POST
		print(contact)
		contact_id = contact['contact_id']
		user = self.request.user
		form = Contact()

		data = {}
		data['success'] = 'Contact Deleted'

		if contact_id:
			update_contact = Contact.objects.get(id=contact_id)
			update_contact.delete()

		return self.render_json_response(data)

	def get_object(self):
		contact_id = self.kwargs.get('contact_id', None)
		print(contact_id)
		return get_object_or_404(Contact, pk=contact_id )

class LogoutView(View):
	def get(self, request):
		user_logout(request)
		return redirect('addressbook:login')

class AjaxContactCreateView(views.JSONResponseMixin, views.AjaxResponseMixin, View):
	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
	    return super(AjaxContactCreateView, self).dispatch(request, *args, **kwargs)

	def post_ajax(self, request, *args, **kwargs):
		user = self.request.user
		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		contact_number = request.POST.get('contact_number')
		address = request.POST.get('address')

		data = {}
		data['first_name'] = first_name
		data['last_name'] = last_name
		data['contact_number'] = contact_number
		data['address'] = address
		data['success'] = "Contact Added"

		contact = Contact()
		contact.user = user
		contact.first_name = first_name
		contact.last_name = last_name
		contact.contact_number = contact_number
		contact.address = address
		contact.save()

		print(data)
		return self.render_json_response(data)

class AjaxContactUpdateView(views.JSONResponseMixin, views.AjaxResponseMixin, View):
	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
	    return super(AjaxContactUpdateView, self).dispatch(request, *args, **kwargs)

	def post_ajax(self, request, *args, **kwargs):
		user = self.request.user
		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		contact_number = request.POST.get('contact_number')
		address = request.POST.get('address')

		data = {}
		data['first_name'] = first_name
		data['last_name'] = last_name
		data['contact_number'] = contact_number
		data['address'] = address

		contact = Contact()
		contact.user = user
		contact.first_name = first_name
		contact.last_name = last_name
		contact.contact_number = contact_number
		contact.address = address
		contact.save()

		print(data)
		return self.render_json_response(data)

def export_csv(request):
	queryset = Contact.objects.defer('id', 'user').filter(user=request.user)
	contact_resource = ContactResource()
	dataset = contact_resource.export(queryset)
	response = HttpResponse(dataset.csv, content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="contacts.csv"'
	return response

def import_csv(request):
	if request.method == 'POST':
		contact = Contact.objects.filter(user=request.user)
		contacts_resource = ContactResource()
		dataset = Dataset()
		new_contacts = request.FILES['import-csv']

		try:
			imported_data = dataset.load(new_contacts.read().decode('utf-8'),format='csv')
			dataset.headers['user'] = request.user.id
			contacts_resource.import_data(dataset, dry_run=False)

		except:
			print(request.user.id)

	return render(request, 'addressbook/import.html', {})

addressbook/templates/addressbook/add_contact.html
{% extends 'addressbook/base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-md-offset-4 add-form">
			<h1>Add Contact</h1>
			<form action="" method="POST">{% csrf_token %}
				<div class="form-group">
					<label for="{{ form.first_name.id_for_label }}">First Name*</label>
					{{ form.first_name }}
					{{ form.first_name.errors }}
				</div>
				<div class="form-group">
					<label for="{{ form.first_name.id_for_label }}">Last Name*</label>
					{{ form.last_name }}
					{{ form.last_name.errors }}
				</div>
				<div class="form-group">
					<label for="{{ form.first_name.id_for_label }}">Contact Number*</label>
					{{ form.contact_number }}
					{{ form.contact_number.errors }}
				</div>
				<div class="form-group">
					<label for="{{ form.first_name.id_for_label }}">Address*</label>
					{{ form.address }}
					{{ form.address.errors }}
				</div>
				<button type="submit" class="btn btn-primary">Add Contact</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

addressbook/templates/addressbook/base.html
{% load staticfiles %}

<html>
    <head>
        <title>Address Book</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'addressbook/css/style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="row">
                    <div class="navbar-header col-md-8">
                        <a class="navbar-brand" href="/">Address Book</a>
                    </div>
                    <ul class="nav navbar-nav col-md-4">
                      <li><a href="#" data-toggle="modal" data-target="#modal-add" data-id="">Add Contact</a></li>
                      <li><a href="{% url 'addressbook:import_csv' %}">Import CSV</a></li>
                      <li><a href="{% url 'addressbook:export_csv' %}">Export CSV</a></li>
                      <li><a href="{% url 'addressbook:logout' %}">Log Out</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
    {% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        $('#add-contact').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: {% url 'addressbook:add_contact' %},
                data: {
                    first_name: $('#id_first_name').val(),
                    last_name: $('#id_last_name').val(),
                    contact_number: $('#id_contact_number').val(),
                    address: $('#id_address').val(),
                },
                success: function(json_response) {
                    $.get("/", function(json_response) {
                        $('#contact-table').html($(json_response).find('#contact-table').html());
                        $('#add-contact')[0].reset();
                    });
                    $("#message").html(json_response.success)
                    $("#modal-add").modal('hide')
                    $('.modal-backdrop').remove()
                },
                error: function(json_response) {
                  alert(JSON.stringify(json_response))
                },
            });
        });
    </script>
    {% endblock %}
</html>

addressbook/templates/addressbook/delete_contact.html
{% load staticfiles %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<form action="" id="delete-contact" class="delete-form-{{contact.id}}">{% csrf_token %}
				    <h4>Are you sure you want to delete contact "{{ object }}"?</h4>
				    <input type="submit" value="Confirm" class="btn btn-primary btn-md" />
				    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</form>
			</div>
		</div>
	</div>
	{% block script %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script>
		$("#delete-contact").on('submit', function(e){
			e.preventDefault()
			$.ajax({
				type: "POST",
				url: "{% url 'addressbook:delete_contact' contact.id %}",
				data: {
					csrfmiddlewaretoken: '{{ csrf_token }}',
					contact_id: '{{ contact.id }}'
				},
				success: function(json_response) {
				    $.get("/", function(json_response) {
				        $("body").html(json_response)
				        $('#message').html('<h3>Contact Deleted</h3>')
				    }); 
				    $("#modal-body-delete").modal('hide')
				    $('.modal-backdrop').remove()
				},
				error: function(json_response) {
				  alert(JSON.stringify(json_response))
				},
			});
		});
	</script>
	{% endblock %}

addressbook/templates/addressbook/delete_contactcopy.html
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<form action="" id="delete-contact" class="delete-form-{{contact.id}}">{% csrf_token %}
			    <h4>Are you sure you want to delete contact "{{ object }}"?</h4>
			    <input type="submit" value="Confirm" class="btn btn-primary btn-md" />
			    <input type="button" value="Cancel" class="btn btn-danger btn-md" id="cancel-button-delete"/>
			</form>
		</div>
	</div>
</div>
<script>
	$("#delete-contact").on('submit', function(e){
		e.preventDefault()
		$.ajax({
			type: "POST",
			url: "{% url 'addressbook:delete_contact' contact.id %}",
			data: {
				csrfmiddlewaretoken: '{{ csrf_token }}',
				contact_id: '{{ contact.id }}'
			},
			success: function(json_response) {
			    $.get("/", function(json_response) {
			        $('#contact-table').html($(json_response).find('#contact-table').html());
			        $('#message').html('<h3>Contact Deleted</h3>')
			    }); 
			    $("#modal-body-delete").modal('hide')
			},
			error: function(json_response) {
			  alert(JSON.stringify(json_response))
			},
		});
		$("#modal-body-delete").modal('hide')
	});

	$('#cancel-button-delete').on('click', function(){
		$("#modal-body-delete").modal('hide')
	});
</script>

addressbook/templates/addressbook/edit_contact.html
{% load staticfiles %}

<html>
	<head>
		<title>Address Book</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'addressbook/css/style.css' %}">
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-4 col-md-offset-4 add-form">
					<h1>Update Contact</h1>
					<form action="" id="update-contact" class="update-form-{{contact.id}}" >{% csrf_token %}
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">First Name*</label>
							{{ form.first_name }}
							{{ form.first_name.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Last Name*</label>
							{{ form.last_name }}
							{{ form.last_name.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Contact Number*</label>
							{{ form.contact_number }}
							{{ form.contact_number.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Address*</label>
							{{ form.address }}
							{{ form.address.errors }}
						</div>
						<button type="submit" class="btn btn-primary">Update</button>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</form>
				</div>
			</div>
		</div>
	</body>
	{% block script %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script>
		$("#update-contact").on('submit', function(e){
		    e.preventDefault();
		    $.ajax({
		        type: "POST",
		        url: "{% url 'addressbook:edit_contact' contact.id %}",
		        data: {
		            first_name: $('.update-form-{{contact.id}} :input[name=first_name]').val(),
		            last_name: $('.update-form-{{contact.id}} :input[name=last_name]').val(),
		            contact_number: $('.update-form-{{contact.id}} :input[name=contact_number]').val(),
		            address: $('.update-form-{{contact.id}} :input[name=address]').val(),
		            csrfmiddlewaretoken: '{{ csrf_token }}',
		            contact_id: '{{ contact.id }}'
		        },
		        success: function(json_response) {
		            $.get("/", function(json_response) {
		                $("body").html(json_response)
		                $("#message").html(json_response.success)
		                $('.modal-backdrop').remove()
		            }); 
		        },
		        error: function(json_response) {
		          alert(JSON.stringify(json_response))
		        },
		    });
		});

	</script>
	{% endblock %}
</html>

addressbook/templates/addressbook/home.html
{% extends 'addressbook/base.html' %}

{% block content %}
<html>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div id="message"></div>
					<table class="table" id="contact-table">
						<tr>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Contact Number</th>
							<th>Address</th>
						</tr>
						{% for contact in contacts %}
						<tr>
							<td> {{ contact.first_name}} </td>
							<td> {{ contact.last_name}} </td>
							<td> {{ contact.contact_number }} </td>
							<td> {{ contact.address}} </td>
							<td> <a href="{% url 'addressbook:edit_contact' contact.id %}" data-toggle="modal" data-target="#modal-body-update" data-id="" class="btn btn-primary btn-md active">Edit Contact</a> </td>
							<td> <a href="{% url 'addressbook:delete_contact' contact.id %}" data-toggle="modal" data-target="#modal-body-delete" class="btn btn-danger btn-md active" aria-disabled="true">Delete</a></td>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</body>
	<div id="modal-add" class="modal fade" role="dialog">
		<div class="modal-dialog">
		    <div class="modal-content">
		        <div class="modal-header">
		            <button type="button" class="close" data-dismiss="modal">&times;</button>
		            <h4 class="modal-title" style="text-align-last: center">Add Contact</h4>
		        </div>
		        <div class="modal-body add-form">
					<form id="add-contact" name="add_contact">
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">First Name*</label>
							{{ form.first_name }}
							{{ form.first_name.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Last Name*</label>
							{{ form.last_name }}
							{{ form.last_name.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Contact Number*</label>
							{{ form.contact_number }}
							{{ form.contact_number.errors }}
						</div>
						<div class="form-group">
							<label for="{{ form.first_name.id_for_label }}">Address*</label>
							{{ form.address }}
							{{ form.address.errors }}
						</div>
						<div class="modal-footer">
							<button type="submit" class="btn btn-primary">Add Contact</button>
						    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</form>
		        </div>
		    </div>
		</div>
	</div>
<div class="modal modal-body-update fade" id="modal-body-update" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>
<div class="modal modal-body-delete fade" id="modal-body-delete" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>
</html>
{% endblock %}

addressbook/templates/addressbook/import.html
{% extends 'addressbook/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="import-csv">
    <button type="submit">Upload</button>
    <p>{{ error }}</p>
  </form>
  <a href="{% url 'addressbook:home' %}" role="button" class="btn btn-primary btn-lg active" aria-disabled="true">Go Back</a>
{% endblock %}

addressbook/templates/addressbook/login.html
{% load staticfiles %}

<html>
    <head>
        <title>Address Book</title>
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'addressbook/css/style-login.css' %}">
        <link rel="stylesheet" href="{% static 'addressbook/css/form-elements.css' %}">
        <link rel="stylesheet" href="{% static 'addressbook/css/font-awesome.min.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-box">
                        <div class="form-top form-blue">
                            <div class="form-top-left">
                                <h3>Login to our site</h3>
                                <p>Enter username and password to log on:</p>
                            </div>
                        </div>
                        <div class="form-bottom">
                            <form role="form" action="" method="POST" class="login-form">{% csrf_token %}
                                <div class="form-group">
                                    <label class="sr-only" for="form-username">Username</label>
                                    <input type="text" name="username" placeholder="Username..." class="form-username form-control" id="form-username">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="form-password">Password</label>
                                    <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                                </div>
                                <input type="submit" name="login" class="btn">
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-box">
                        <div class="form-top form-blue">
                            <div class="form-top-left">
                                <h3>Sign up now</h3>
                                <p>Fill in the form below to get instant access:</p>
                            </div>
                        </div>
                        <div class="form-bottom font-blue">
                            <form role="form" method="POST" class="registration-form">{% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <input type="submit" name="signup" class="btn" value="Sign Up"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>